#!/usr/bin/env bash

function BuildPackage {
  echo "Building package..."
  cd /workspaces/pyVisualCrossing
  python -m build
  echo "Package built!"
}

function UploadPackage {
  echo "Uploading package..."
  twine upload /workspaces/pyVisualCrossing/dist/*
  echo "Package uploaded!"
}
